version: 2
jobs:
  build:
    working_directory: ~/phovea
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - run: #remove all resolved github dependencies
          name: delete-vcs-dependencies
          command: |
            (grep -l '._resolved.: .\(git[^:]*\|bitbucket\):' ./node_modules/*/package.json || true) | xargs -r dirname | xargs -r rm -rf
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
          - ./node_modules
      - run: #install all dependencies
          name: install-npm-wee2
          command: npm install
      - run:
          name: dist
          command: npm run dist
      - store_artifacts:
          path: dist
      - run: #update build doc and readme
          name: update api
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] ; then
                git clone git@github.com:datavisyn/lineup.js.org.git
                cd lineup.js.org
                rm -rf "${CIRCLE_BRANCH}/"
                if [ "${CIRCLE_BRANCH}" == "develop" ] ; then
                  rm -rf ../build/docs
                fi
                mv ../build "${CIRCLE_BRANCH}"
                cp ../demo/* "${CIRCLE_BRANCH}/"
                git config user.email "samuel_gratzl@gmx.at"
                git config user.name "Samuel Gratzl"
                git add -A
                git commit -m "auto updating ${CIRCLE_BRANCH}" -m "trigger: ${CIRCLE_BUILD_URL}"
                git push origin master
            fi

